import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="flex h-screen flex-col items-center justify-center p-2 bg-neutral-800 text-gray-200">
				{children}
			</body>
		</html>
	);
}
