project:
  output-dir: output
  # post-render: [_scripts/rename.py]

bibliography: [references.json]

filters:
  - latex-environment

commands: [hl]

execute:
  freeze: auto
  cache: refresh
  include: false
  echo: false
  output: false
  message: false
  enabled: true
